### ISSUE TITLE
Incorrect rule name, or misleading docs

### ISSUE THREAD

**Issue by vlascik** [NullVoxPopuli/eslint-plugin-decorator-position#186]
Docs at https://github.com/NullVoxPopuli/eslint-plugin-decorator-position#2-modify-your-eslintrcjs put the name of the `rules` configuration entry as `decorator-position`, but https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/61a7aea34d815497e194a3e1f1d18253fe9c47e8/lib/config/ember.js#L4 exports it as `decorator-position/decorator-position`.

One of those is incorrect, currently, if you try to follow the docs and configure the rules at `decorator-position`, eslint is going to show an error `ESLint: Definition for rule ;decorator-position' was not found.`

**Comment by NullVoxPopuli** [comment]
The examples have the full thing:

https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/master/smoke-tests/integration/position-prettier/.eslintrc.js#L5

So it's an issue with the docs.
I'd happily accept a PR to update the docs :)

**Comment by vlascik** [comment]
You realize fixing it in a README file on your drive and commiting it whenever would take half the characters it took to ask for a PR though, right? :)

**Comment by NullVoxPopuli** [comment]
Yup. And it'd also be less than any of these comments.  I'm on my phone :)

**Comment by vlascik** [comment]
Closed in https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/189
