### ISSUE TITLE
Breaking change between 2.2.6 and 2.2.8

### ISSUE THREAD

**Issue by EvgenyOrekhov** [NullVoxPopuli/eslint-plugin-decorator-position#196]
Now eslint-plugin-decorator-position with default settings suddenly wants property decorators to be on the line above: https://github.com/EvgenyOrekhov/eslint-config-hardcore/blob/cf5c68bf2e2a0e9e5d853266461cde3d3d160b71/sort-class-members-test.js#L33

See https://github.com/EvgenyOrekhov/eslint-config-hardcore/pull/172.

**Comment by NullVoxPopuli** [comment]
Well that wasn't supposed to happen. :(

Can you try to submit a reproduction? Either as an eslint test or reproduction smoke test?

**Comment by EvgenyOrekhov** [comment]
I'm trying, but I can't reproduce it as an ESLint test or reproduction smoke test.

I'm trying to debug it, I can see that `printWidth` ends up being `undefined`, and then `NaN`:

```text
{
  printWidth: undefined,
  overrides: { 'prefer-inline': [ 'decorator' ], above: [ 'decorator' ] }
}
{ inlineLength: 37, printWidth: NaN }
```

Perhaps it has something to do with that?

**Comment by NullVoxPopuli** [comment]
Oh! That could certainly be it! I refactored that stuff
How is your prettier config setup? (Eslint, separate config, etc)

**Comment by EvgenyOrekhov** [comment]
I was able to reproduce the issue by removing this line from the smoke test: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/74f5b366cdc35154f32414b3a45ad1ea8d7f0eb0/smoke-tests/integration/external-config-prettier/.prettierrc.js#L3

**Comment by NullVoxPopuli** [comment]
Excellent find!

I can get a fix pr up today, if you don't want to

**Comment by EvgenyOrekhov** [comment]
> How is your prettier config setup?

In my ESLint config I use `"extends": ["plugin:prettier/recommended"]`, and I do **not** have `.prettierrc.js`. But in some of my apps I use `.prettierrc.js`. The issue is reproducible in both cases when `printWidth` is not defined.

> I can get a fix pr up today, if you don't want to

I'm struggling to figure out your development flow, can't really figure out how to use the smoke tests and whatnot. So, I would appreciate it if you fixed it :)

**Comment by NullVoxPopuli** [comment]
awesome! and thanks for the feedback. I'll try to make the CONTRIBUTING.md useful
