### ISSUE TITLE
Too many "printWidth not set" warnings

### ISSUE THREAD

**Issue by EvgenyOrekhov** [NullVoxPopuli/eslint-plugin-decorator-position#198]
eslint-plugin-decorator-position is spamming my terminal, it gives me the "printWidth not set" warning for every file:

![image](https://user-images.githubusercontent.com/8045060/98568860-9db7cb80-22c2-11eb-91e2-b36ac0d6c61d.png)

That's not useful.

**Comment by NullVoxPopuli** [comment]
Does it go away if you set printWidth in prettier's config?

**Comment by EvgenyOrekhov** [comment]
> Does it go away if you set printWidth in prettier's config?

I'm not using a Prettier config in that project, I'm using the defaults.

**Comment by EvgenyOrekhov** [comment]
We actually have the "always use defaults" policy for Prettier for all our projects. We don't use custom Prettier configs (with some rare exceptions when we need to use some experimental feature, like Glimmer parser).

And I don't see why this warning has to exist at all. The lack of a Prettier config or the lack of the `printWidth` option is usually not a mistake, it is intentional.

**Comment by NullVoxPopuli** [comment]
That's a good point. Hmm

I guess if we could get the prettier default value from prettier itself, instead of hard coding, this custom stuff can all go away

**Comment by NullVoxPopuli** [comment]
ah-ha: https://github.com/prettier/prettier/blob/3d7016e2dc38e3b03df8129c52dd85b1ff9aec60/src/main/core-options.js#L192-L199

If this data is used, then we don't need to warn or use a hard-coded value. _the upstream default can be used, which is much safer_

**Comment by NullVoxPopuli** [comment]
added here: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/202

if there are any issues, pls let me know.
I'm sure this project is still missing a few key test cases
