### ISSUE TITLE
Rename onDifferentLines and onSameLine to above and beside

### ISSUE THREAD

**Issue by Exelord** [NullVoxPopuli/eslint-plugin-decorator-position#3]
What do you think about renaming it to `onNewLines`?

https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/b5af6c25a60d6abe20991a5c0c26b34d0e0dfcae/lib/config/ember.js#L8

**Comment by NullVoxPopuli** [comment]
Any particular reason? What are the semantic differences?

**Comment by Exelord** [comment]
Its about the point of view.
If you look from a decorator perspective the code block is on the same line or on a new line.
From a code block perspective, it is on same line or as it is currently a different line.

So, its whether the positioning of code that relates to decorator or decorator to code :) 

Personally I prefer to position code that relates to a decorator which is the decorator perspective.

**Comment by NullVoxPopuli** [comment]
Hmm. To counter, decorators are augmentations of a property or method or whatever are not the main event. Only an annotation, yeah? so the perspective then falls to the thing being decorated. Maybe the following options?: 'inline' and 'above'?

**Comment by Exelord** [comment]
Boom! Yeah, that describes it best! differentLine is not so specific about the location. inline and above are explicit. This format also is followed in other official eslint rules, eg: https://eslint.org/docs/rules/line-comment-position

**Comment by NullVoxPopuli** [comment]
Nice. :)

Cool. I'm on board with this. Will cause a very fast v2. Lol

**Comment by Exelord** [comment]
Actually when looking at other eslint rules it looks like the standard is `beside` and `above`
