### ISSUE TITLE
Prettier runtime dependency

### ISSUE THREAD

**Issue by bordecal** [NullVoxPopuli/eslint-plugin-decorator-position#337]
Commit a97d8fff481b24c1874325b603920adb43ab219f seems to have removed the runtime dependency on Prettier.  Without this dependency, a consuming project that does not reference Prettier will receive a runtime error during linting:

```
An unhandled exception occurred: Error while loading rule 'decorator-position/decorator-position': Cannot find module 'prettier'
Require stack:
- C:\Code\AgentDash\Frontend\node_modules\eslint-plugin-decorator-position\lib\rules\decorator-position.js
- ...
```

**Comment by NullVoxPopuli** [comment]
Ah! Thanks for reporting this! Prettier had to be moved to a peer dependency because prettier 2.3 changed some formatting, and in monorepos, version resolution is not great and moving to a peer dependency allows the consuming project to determine the prettier version.
Tbh, I'm surprised the existing smoke tests and issue reproduction tests don't cover this 🤔

But yeah, if you want to PR this with a repro, the require should be wrapped with a try catch. 
Otherwise, I can do it tomorrow

**Comment by bordecal** [comment]
Unfortunately, I can't seem to find a way to repro in the smoke tests.  Prettier doesn't appear in the smoke test `node_modules` directory, so I'm guessing the instance from the locally referenced `eslint-plugin-decorator-position` ends up getting used at test runtime. :(

**Comment by NullVoxPopuli** [comment]
well, knowing that there is an exception thrown from the `require`, I can at least "blindly" wrap that in a try-catch, and it wouldn't hurt anything

**Comment by NullVoxPopuli** [comment]
@bordecal can you try this out and see if it fixes things for you? https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/340

**Comment by bordecal** [comment]
It seems to be working fine.  There's no error anymore, and rule violations are detected as expected.  Thanks!

WRT testability, I'm wondering if the directory-climbing (+/- global) module resolution described at https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders might be the culprit.  If so, it might become possible to add tests for this kind of scenario if the project were re-organized to place the `smoke-tests` directory beside the source code directory instead of inside it.  That would presumably require some non-trivial changes to a bunch of test and CI plumbing, so it might not be worthwhile unless this kind of dependency-related issue crops up again...

**Comment by NullVoxPopuli** [comment]
awesome! I'll get that merged and released then.

yeah -- def seems like a thing we can push off until it bothers us again. thanks for looking in to it!

**Comment by tek-ncalinoi** [comment]
Thank you!

**Comment by bordecal** [comment]
Thank you!
