### ISSUE TITLE
Max length

### ISSUE THREAD

**Issue by rwwagner90** [NullVoxPopuli/eslint-plugin-decorator-position#34]
Is there a way to configure a max length? For example, if you had something like:

```js
@alias('foo.bar.baz.someReallyLongPropertyNameThatIsTooLongToBeInlineOrItBreaksPrettier')
myProp;
```

I would like to make `alias` inline always, unless it is too long and would conflict with prettier formatting, basically.

Is there currently a way to do that?

**Comment by NullVoxPopuli** [comment]
afaik, not without specifying a length option in the config.

I would love to integrate with eslint-plugin-prettier and just _get_ the line width passed in some object here: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/master/lib/rules/decorator-position.js#L120

but I don't know if that's possible.

I _think_ the best way to achieve this now is to do something like:

```ts
const prettierConfig = require('./.prettierrc');
rules: {
  'decorator-position/decorator-position': ['error', { lineWidth: prettierConfig.whicheverOptionThisIs }]
}
```
idk

**Comment by rwwagner90** [comment]
@NullVoxPopuli I am fine with specifying a length, It looks like from your suggestion `lineWidth` is what I am after? I didn't see options documented anywhere, but maybe I missed them.

**Comment by NullVoxPopuli** [comment]
`lineWidth` isn't implemented (yet), but I'd happily accept a PR for it ;)

also, looks like `printWidth` is the prettier config name -- https://prettier.io/docs/en/options.html
maybe we should align with that?

**Comment by rwwagner90** [comment]
Ah, gotcha. I'm not sure I currently have the time to dive into it, but perhaps sometime this week.

**Comment by NullVoxPopuli** [comment]
@rwwagner90 can you share an example config for eslint and prettier?

I just tried setting printWidth to 100, and got this output:

**Comment by NullVoxPopuli** [comment]
ah, cause it's the difference between this:

```diff
-  @belongsTo('foo.bar.baz.someReallyLongPropertyNameThatIsTooLongToBeInlineOrItBreaksPrettier.Prettier.is.Set.to.100') myProp;
+  @belongsTo(
+    'foo.bar.baz.someReallyLongPropertyNameThatIsTooLongToBeInlineOrItBreaksPrettier.Prettier.is.Set.to.100'
+  )
+  myProp;
```

**Comment by NullVoxPopuli** [comment]
it could be that @tylerturdenpants has a fix working! and that's why I can't reproduce.

@rwwagner90 can you review this test-case change (and maybe everything in `smoke-tests/-rules/position-prettier/default.js`), to see if it covers your scenario?
https://github.com/tylerturdenpants/eslint-plugin-decorator-position/pull/1
