### ISSUE TITLE
Add a possibility to define defaults

### ISSUE THREAD

**Issue by Exelord** [NullVoxPopuli/eslint-plugin-decorator-position#4]
It would be nice if we could set defaults for properties, functions, classes and accessors, example:

```
'decorator-position': [
      'error',
      {
        propertyStartegy: 'sameLine',
        functionStrategy: 'newLine',
        classStartegy: 'newLine',
        accessorStartegy: 'sameLine'
      }
    ]
```

**Comment by NullVoxPopuli** [comment]
I agree! This'll be a great addition

**Comment by Exelord** [comment]
even more advanced, we can allow defining the strategy based by multi-line and single-line

```
'decorator-position': [
      'error',
      {
        propertyStartegy: { singleLine: 'sameLine', multiLine: 'newLine' },
        functionStrategy: { singleLine: 'sameLine', multiLine: 'newLine' },
        classStartegy: 'newLine',
        accessorStartegy: 'sameLine'
      }
    ]
```

**Comment by NullVoxPopuli** [comment]
> propertyStartegy: { singleLine: 'sameLine'

Can you give an example?

**Comment by Exelord** [comment]
```
class MyClass {
  @log singleLineProperty = 'I am single line';
  
  @log
  multiLineProperty = showAlert(() => {
    alert('I am multi line')
  })
}
```

**Comment by NullVoxPopuli** [comment]
Gotchya! Yeah, I think something like this is doable

**Comment by NullVoxPopuli** [comment]
Implemented by https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/9

**Comment by Exelord** [comment]
WHAAAAT? Are you serious? <3 <3 <3 <3

**Comment by NullVoxPopuli** [comment]
yeah, that was a good idea. didn't take long to implement, as the logic was already mostly there. :)

diff: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/9/files#diff-2818a75e6e0e109e9d2fe15be45813f4L89

**Comment by Exelord** [comment]
Im only missing the multi/single line support then :D 
For single-line functions, l would like to use inline version of the decorators
```
@callback dummy() {} 
```
and for multiline properties `above` 😅

**Comment by NullVoxPopuli** [comment]
Can you open a new issue for that?
