### ISSUE TITLE
enforcing @action to be on a separate line

### ISSUE THREAD

**Issue by iamdtang** [NullVoxPopuli/eslint-plugin-decorator-position#474]
<img width="951" alt="Screen Shot 2022-02-02 at 4 14 29 PM" src="https://user-images.githubusercontent.com/687449/152259551-a260a73d-ad88-4919-be22-7d2c16a0c375.png">

This is what's happening for me. The `one` method fails linting as expected, but as soon as I define a body like in method `two`, linting passes when I expect it to fail. This is all of the code:

```js
import Component from '@glimmer/component';
import { action } from '@ember/object';

export default class Foo extends Component {
  @action one() {}

  @action two() {
    return 2;
  }
}
```

**Comment by NullVoxPopuli** [comment]
:wave: Hello!! 

what's your lint config look like?

**Comment by NullVoxPopuli** [comment]
Reason I ask is because I added this test: 
![image](https://user-images.githubusercontent.com/199018/152261723-614a6202-c980-48a5-a285-f3427efe0311.png)
and it passed :thinking:

**Comment by skaterdav85** [comment]
hey 👋!

Here is my config:

```json
{
  "decorator-position/decorator-position": [
    "error",
    {
      "properties": "prefer-inline",
      "methods": "above"
    }
  ]
}
```

With the above, shouldn't it fail if `@action` is inline?

**Comment by NullVoxPopuli** [comment]
yeah, I'd expect two errors, one for each action.

**Comment by NullVoxPopuli** [comment]
if you run `eslint . --fix`, what happens?

**Comment by skaterdav85** [comment]
`eslint . --fix` only fixes the first one which is failing. I created a reproduction repo here: https://github.com/skaterdav85/decorator-linting-reproduction

**Comment by NullVoxPopuli** [comment]
Thanks, I've copied that into the test suite here: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/475

dunno when I'll have time to fix -- but thanks for reporting!!!
