### ISSUE TITLE
Making a rule that disallows decorators altogether

### ISSUE THREAD

**Issue by palnes** [NullVoxPopuli/eslint-plugin-decorator-position#606]
Don't want them. At all. 😁

**Comment by NullVoxPopuli** [comment]
I can take a PR for this if you do the work <3

the rule would end up being enabled as:
```js
  'decorator-position/forbid-decorators': ['error'],
```

also, what do you have against decorators? they're almost Stage 4

**Comment by palnes** [comment]
I was looking for something like this, and you were the closest. Terribly sorry.

As for decorators as a concept, perfectly fine. this is just for a brittle project where there has been a lot of "early adoption" reminding me more of the React mixin days. :) thank you for making this plugin tho, have a nice weekend. :)
