### ISSUE TITLE
decorator-position affecting indent

### ISSUE THREAD

**Issue by nunocunha** [NullVoxPopuli/eslint-plugin-decorator-position#701]
# Description
No entirely sure on how to create a reproduction example, but mixing [indent](https://eslint.org/docs/latest/rules/indent) with [decorator-position/decorator-position](https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/main/docs/rules/decorator-position.md) makes ESLint go crazy.

`.eslintrc.js`
```js
module.exports = {
    extends: ['eslint:recommended'],
    root: true,
    overrides: [
        {
            files: ['*.js', '*.ts'],
            plugins: ['decorator-position'],
            rules: {
                'decorator-position/decorator-position': ['error', {
                    methods: 'above',
                    properties: 'above'
                }],
                indent: ['error', 2]
            }
        }
    ]
};
```

`example.js`
```js
function Decorator() {
  console.log();
}

    @Decorator() // This line SHOULD have an indent error (has 4 spaces, should have 0), but does NOT 
    class Class { // This line has the correct indent error (has 4 spaces, should have 0)
@Decorator() // This line SHOULD have an indent error (has 0 spaces, should have 2), but does NOT
  prop1; // This line is correct

    @Decorator() // This line SHOULD have an indent error (has 4 spaces, should have 2), but does NOT
      prop2; // This line SHOULD have an indent error (has 6 spaces, should have 2), but does NOT
} // This line should NOT have an indent error (has 0 spaces, should have 0)
```

# Expected (`eslint ./example.js --fix`)
```js
function Decorator() {
  console.log();
}

@Decorator() 
class Class {
  @Decorator()
  prop1;

  @Decorator()
  prop2;
}
```

# Actual (`eslint ./example --fix`)
```js
function Decorator() {
  console.log();
}

    @Decorator() 
class Class {
@Decorator()
  prop1;

    @Decorator()
      prop2;
    }
```

# Notes
It seems that `decorator-position/decorator-position` is affecting `indent`, as ESLint expects the line after the decorator to have one more indent level than the decorator.

**Comment by NullVoxPopuli** [comment]
I'm kind of surprised anything is happening at all with the class decorator, tbh.

https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/main/lib/rules/decorator-position.js#L171

The AST hasn't specified anything for the class decorator: 
![image](https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/assets/199018/2285b60d-b48b-4160-b51d-108e63aa1932)


So that's kinda goofy.

If you have time for a few failing tests in a PR, that'd be super helpful <3

**Comment by nunocunha** [comment]
Apparently this is an issue with vanilla ESLint and TypeScript. I was trying to use "indent" which doesn't support TypeScript for both JS and TS. More info [here](https://github.com/typescript-eslint/typescript-eslint/issues/1232). So I ended up separating "indent" for JS only and "@typescript-eslint/indent" for TS, as one should do.

Sorry I took a while to get back to you.
