### ISSUE TITLE
Support ESLint v9

### ISSUE THREAD

**Issue by Logicer16** [NullVoxPopuli/eslint-plugin-decorator-position#721]
ESLint v9 was [officially released](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/) on the 5th of April. This notably also includes making the new flat config format the default. A migration guide can be found [here](https://eslint.org/docs/latest/use/migrate-to-9.0.0#breaking-changes-for-plugin-developers).

**Comment by NullVoxPopuli** [comment]
ooo yeees I was waiting for this!

**Comment by NullVoxPopuli** [comment]
I think also, I was waiting on `@typescript-eslint` to provide flat configs, and it looks like they have, so I think migration to flat config in this repo is unblocked!

**Comment by NullVoxPopuli** [comment]
ESLint 9 is now supported in v6, via #733
