### ISSUE TITLE
Possible to define that multiple decorators should always be on different lines?

### ISSUE THREAD

**Issue by lougreenwood** [NullVoxPopuli/eslint-plugin-decorator-position#8]
We would like to stack multiple lines of decorators, e.g:

```js

//example may not be legit
@memo
@task
thingy = ...
```

However, it seems that this isn't possible with the lint against with the linters current capabilities?

**Comment by NullVoxPopuli** [comment]
What sorts of things would you like to protect against with multiple decorators? 

I'm open to supporting them in some way

**Comment by NullVoxPopuli** [comment]
like, is this possible: `@memo @task thing = ...` (I've never tried inlining multiple decorators)

maybe this rule would be called:

`decorator-position/multiple-decorators`: 'error'` I see no reason why there'd be another way to organize multiple decorators

**Comment by lougreenwood** [comment]
At the moment, the only use case I can think of would be to optionally define that inline is invalid, and multiple lines is valid:

bad:
```js
@memo @task thing = ...
```

bad:
```js
@memo @task
thing = ...
```

good:
```js
@memo
@task
thingy = ...
```

**Comment by lougreenwood** [comment]
obviously, ideally it would be possible to define any one of those variations as valid 😉

**Comment by NullVoxPopuli** [comment]
> ideally it would be possible to define any one of those variations as valid

would it? lol. does anyone actually want multiple inline decorators?

**Comment by nightire** [comment]
> would it? lol. does anyone actually want multiple inline decorators?

Subjectively speaking, no.

**Comment by lougreenwood** [comment]
My thinking was that if this rule were to be added, it shouldn't be at the expense of not being able to disable it (where "disabling" means allowing either of the inline formats, since it seems that there are only 3 valid variations).

But I guess if people really don't like multiple inline (i.e either of the `bad` formats I suggested [here](https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/issues/8#issuecomment-604027403)), then it's not necessary.

(Side note, I hadn't properly considered the "bad 2" option before, but after seeing it in my examples I'm now a little bit curious about it.... :D)

**Comment by NullVoxPopuli** [comment]
>  it shouldn't be at the expense of not being able to disable it 

Of for sure. Since this'd be a new rule, a person would set it to 'off' or 'warn' or whichever.

At least for the first iteration, I think it'll be easy to either enforce and fix a stack, or not at all. Later on down the road, a config could be added for other things.

**Comment by NullVoxPopuli** [comment]
it turns out that this:
```
@memo @task
thing = ...
``` 
is converted to
```
@memo 
@task
thing = ...
```
when using prettier

**Comment by NullVoxPopuli** [comment]
https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOAAgGYQQUBG6ATjiWZjOmANYDcrLpAWSo16THAEsoqKXD5R+IiAApigsuiQ4AjPwC+ASjHNIAWwAOMsOngATeXpAAaEBHMwJ0TMlBNGEAHcABSYEbxR0VAD0AE9vFzpGTi44GABlc04pAHNkGEYAVzgXAAsYU1QAdRKJeExMsDg0sNqJADdamORwbGcQKUw4RhggpOzTdGRKSMGXACtMAA8AISTuVLT0UzgAGVkpmeKQBcW0nNQ4AEUCiHgD1FmQTMZBxm6GOjhUPvNGKRhKhJbDASsgABwABhcvwgg0qSXM3V+cFebTgfQAjjd4KM3OEQFgALRQOBwWxkvqMOBYiRU0bocaTJDTB5HQamCR5Qps85XbHo5mHFwcOiA4GgpAAJmFSQkMig2QAwhBTBNuiiAKx9AqDAAq6Do4RZjzaRQAklBybA0mA-u48Ja0jAYhd7oM9HogA

![image](https://user-images.githubusercontent.com/199018/77702033-f0d84a80-6f8d-11ea-9f55-b80606f5e6a2.png)

so that just leaves `@foo bar inline` unhandled, if someone wanted all multi-decorators stacked.

**Comment by NullVoxPopuli** [comment]
Closing, as this is handled by prettier, and I don't think that we need to duplicate the behavior?
Though, if someone has a good argument for re-implementing this, I'd be open to a PR or something :)
